#%RAML 1.0 constants-iso-unit
["4G", "AA", "BE", "BG", "BJ", "BL", "BLI", "BND", "BO", "BX", "C4", "C5", "C62", "CA", "CG", "CH", "CL", "CLT", "CMK", "CMQ", "CMT", "CQ", "CS", "CT", "CV", "D64", "D97", "DAY", "DI", "DPC", "DZN", "EA", "ETI", "EV", "FOI", "FOT", "GRM", "HUR", "JR", "KGM", "KIS", "KMT", "KST", "KT", "LBR", "LTR", "M4", "MC", "MGM", "MLT", "MMT", "MTK", "MTQ", "MTR", "OP", "PA", "PAD", "PD", "PF", "PK", "PR", "QR", "RD", "RL", "RM", "RO", "SA", "SCH", "SET", "SPD", "SR", "ST", "STK", "TAB", "TC", "TN", "TNE", "TU", "TUC", "WEE", "WP", "Z3"]